# Generated by Django 2.0 on 2017-12-27 07:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('mfal', models.CharField(max_length=150)),
                ('preference', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('basesp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sp.BaseSP')),
            ],
            bases=('sp.basesp',),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('basesp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sp.BaseSP')),
                ('ponderacion', models.PositiveSmallIntegerField()),
            ],
            bases=('sp.basesp',),
        ),
    ]
