# Generated by Django 2.0.1 on 2018-01-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0003_auto_20180103_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesp',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='mfal',
            name='mfal_code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='mfal',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
